import { ManualTaskSeed } from './courseTasks';

export const mockManualTasks: ManualTaskSeed[] = [
  {
    id: 'manual-informe-escanio-ecom-tci',
    title: 'Solicitar confirmación de calendario a la escuela',
    description: 'Revisar con la escuela responsable si mantiene las fechas previstas antes de preparar el borrador definitivo.',
    courseId: 'ecom-tci-2026',
    courseCode: '60046 2026 001',
    courseName: 'ECOM TCI para Suboficiales',
    dueDate: '2026-05-04',
    priority: 'alta',
    status: 'pendiente',
    responsible: 'DIENA - Perfeccionamiento',
    linkType: 'curso',
    relatedLabel: '60046 2026 001',
    createdAt: '2026-04-27',
  },
  {
    id: 'manual-expediente-seg-resultados',
    title: 'Preparar oficio de solicitud de resultados',
    description: 'Borrador de oficio para solicitar resultados de pruebas físicas y reconocimiento médico.',
    courseId: 'ecom-seg-2026',
    courseCode: '60181 2026 001',
    courseName: 'ECOM SEG para Suboficiales',
    dueDate: '2026-06-15',
    priority: 'media',
    status: 'en_curso',
    responsible: 'Gestor DIENA',
    linkType: 'documento',
    relatedLabel: 'Oficio solicitud resultados',
    createdAt: '2026-04-27',
  },
  {
    id: 'manual-instancia-e2t-ciber',
    title: 'Analizar posible instancia vinculada al curso',
    description: 'Revisar si la solicitud afecta a nombramiento, baja, aplazamiento o condiciones de la convocatoria.',
    courseId: 'e2t-tci-ciber-2026',
    courseCode: '62T04 2026 001',
    courseName: 'E2T TCI-Ciber para Oficiales',
    dueDate: '2026-05-10',
    priority: 'media',
    status: 'pendiente',
    responsible: 'DIENA - Sección de Perfeccionamiento',
    linkType: 'instancia',
    relatedLabel: 'Instancia pendiente de clasificación',
    createdAt: '2026-04-27',
  },
];
